apiVersion: v1
kind: Service

metadata:
  name: php-fpm-service

spec:
  clusterIP: 10.109.238.2
  type: ClusterIP
  selector:
    app: php-fpm
  ports:
  -   name: php-fpm-port
      targetPort: 9000
      port: 9000