apiVersion: apps/v1
kind: Deployment

metadata:
  name: php-fpm-deployment
  labels:
    app: php-fpm

spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:

      containers:
      -   name: php-fpm
          imagePullPolicy: Always
          image: bitnami/php-fpm:7.2
          ports:
          -   containerPort: 80
          livenessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 30
              periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 3
          volumeMounts:
          - mountPath: "/var/www/html/nextcloud"
            name: nextcloud-persistent-volume

      volumes:
          - name: nextcloud-persistent-volume
            persistentVolumeClaim:
              claimName: nextcloud-pvc

      restartPolicy: Always
