FROM fedora:29

LABEL Damian Malikiah McCarthy

RUN echo "zchunk=false" >> /etc/dnf/dnf.conf

RUN dnf clean all && dnf -y update --releasever=29 && dnf -y install php php-cli php-fpm php-mysqlnd php-zip php-devel php-gd php-mcrypt php-mbstring php-curl php-xml php-pear php-bcmath php-json

RUN dnf -y install git

RUN mkdir -p /var/run/php-fpm
RUN mkdir -p /var/run/php
#RUN sed -i 's:listen = /run/php-fpm/www.sock:listen = /var/run/php/php7.2-fpm.sock:' /etc/php-fpm.d/www.conf
#RUN sed -i 's;listen = /run/php-fpm/www.sock;listen = 127.0.0.1:9000;' /etc/php-fpm.d/www.conf
#RUN sed -i 's;listen.allowed_clients = 127.0.0.1;listen.allowed_clients = ;' /etc/php-fpm.d/www.conf
RUN git clone https://github.com/Malikiah/kubernetes-resources.git

RUN cp -rf kubernetes-resources/php-fpm/www.conf /etc/php-fpm.d/

RUN rm -rf kubernetes-resources

EXPOSE 9000
ENTRYPOINT /usr/sbin/php-fpm -F
