apiVersion: apps/v1
kind: Deployment

metadata:
  name: php-fpm-deployment
  labels:
    app: php-fpm

spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:

      containers:
      -   name: php-fpm
          imagePullPolicy: Always
          image: php:7.2.22-fpm
          ports:
          -   containerPort: 9000
        
          volumeMounts:
          - mountPath: "/var/www/html/nextcloud"
            name: nextcloud-persistent-volume

      volumes:
          - name: nextcloud-persistent-volume
            persistentVolumeClaim:
              claimName: nextcloud-pvc

      restartPolicy: Always
