FROM fedora:29

MAINTAINER Damian Malikiah McCarthy

RUN dnf -y update && dnf -y install nginx git

RUN dnf -y install php php-cli php-fpm php-mysqlnd php-zip php-devel php-gd php-mcrypt php-mbstring php-curl php-xml php-pear php-bcmath php-json

RUN dnf -y install wget bzip2

RUN wget https://download.nextcloud.com/server/releases/nextcloud-16.0.3.tar.bz2 && mkdir -p /var/www/html/nextcloud && tar -xvf ./nextcloud-16.0.3.tar.bz2 -C /var/www/html/nextcloud && chown -R nginx:nginx /var/www/html/nextcloud/nextcloud && mkdir -p /var/www/html/nextcloud/nextcloud-data

RUN rm -rf nextcloud-16.0.3.tar.bz2

RUN echo "daemon off;" >> /etc/nginx/nginx.conf

RUN git init
RUN git config core.sparsecheckout true
RUN echo nginx/conf.d > .git/info/sparse-checkout
RUN git remote add origin -f https://github.com/Malikiah/kubernetes-resources.git
RUN git pull origin master

RUN cp -r ./nginx/conf.d/cloud.malikiah.io.conf /etc/nginx/conf.d

RUN rm -rf nginx .git

EXPOSE 80
CMD ["php-fpm"]
CMD ["nginx"]


