FROM fedora:29

MAINTAINER Damian Malikiah McCarthy

VOLUME letsencrypt:/etc/letsencrypt/live

RUN dnf -y update && dnf -y install nginx libcurl

RUN dnf -y install php php-cli php-fpm php-mysqlnd php-zip php-devel php-gd php-mcrypt php-mbstring php-curl php-xml php-pear php-bcmath php-json

RUN dnf -y install wget bzip2

RUN wget https://download.nextcloud.com/server/releases/nextcloud-16.0.3.tar.bz2 && mkdir -p /var/www/html/nextcloud && tar -xvf ./nextcloud-16.0.3.tar.bz2 -C /var/www/html/nextcloud && chown -R nginx:nginx /var/www/html/nextcloud/nextcloud && mkdir -p /var/www/html/nextcloud/nextcloud-data

RUN rm -rf nextcloud-16.0.3.tar.bz2

RUN echo "daemon off;" >> /etc/nginx/nginx.conf

RUN curl https://raw.githubusercontent.com/Malikiah/kubernetes-resources/master/nginx/conf.d/cloud.malikiah.io.conf > /etc/nginx/conf.d/cloud.malikiah.io

EXPOSE 80
CMD ["php-fpm"]
CMD ["nginx"]


