apiVersion: v1
kind: Service
metadata:
    name: nextcloud-service
spec:
    type: NodePort
    selector:
        app: nextcloud
    ports:
    -   name: nextcloud-port
        targetPort: 30002
        port: 30002
        nodePort: 30002