apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: nextcloud-pvc

spec:
  accessModes:
    - ReadWriteOnce
  PersistentVolumeClaimPolicy: Retain

  resources:
    requests:
  capacity:
    storage: 500Gi
  hostPath:
    path: "/var/www/html/nextcloud"