apiVersion: apps/v1
kind: Deployment

metadata:
  name: nextcloud-deployment
  labels:
    app: nextcloud

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      nodeName: fra1-elliptic-node-01
      containers:
      -   name: nextcloud
          image: nextcloud:fpm
          
          livenessProbe:
              httpGet:
                path: /
                port: 9000
              initialDelaySeconds: 30
              periodSeconds: 30
            readinessProbe:
              httpGet:
                path: /
                port: 9000
              initialDelaySeconds: 15
              periodSeconds: 3
          env:
          -   name: MYSQL_DATABASE
                valueFrom:
                  secretKeyRef:
                    key: MYSQL_DATABASE
                    name: db-secrets
          volumeMounts:
          -   mountPath: /home/malikiah/public_html/nextcloud
              name: nextcloud-persistent-storage
      restartPolicy: Always
      volumes:
      -   name: nextcloud-persistent-storage
          persistentVolumeClaim:
            claimName: nextcloud-pvc