apiVersion: v1
kind: Service

metadata:
  name: nextcloud-service

spec:
  type: NodePort
  selector:
    app: nextcloud
  ports:
  -   name: nextcloud-port
      targetPort: 9000
      port: 9000
      nodePort: 30009