apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: nextcloud-pvc
  label:
    type: local

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 500Gi

