apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-persistent-volume
  labels:
    type: local
    
spec:
  storageClassName: manua
  capacity:
    storage: 500Gi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: "/var/www/html/nextcloud"