apiVersion: apps/v1
kind: Deployment

metadata:
  name: nextcloud-deployment
  labels:
    app: nextcloud

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:

      containers:
      -   name: nextcloud
          imagePullPolicy: Always
          image: malikiah/nextcloud:latest
          ports:
          -   containerPort: 80
          livenessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 30
              periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 3
          volumeMounts:
          - mountPath: "/var/www/html/nextcloud"
            name: nextcloud-pvc

      volumes:
          - name: nextcloud-persistent-volume
            persistentVolumeClaim:
              claimName: nextcloud-pvc

      restartPolicy: Always
