apiVersion: apps/v1
kind: Deployment

metadata:
  name: nextcloud-deployment
  labels:
    app: nextcloud

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      nodeName: fra1-elliptic-node-01
      containers:
      -   name: nextcloud
          image: nextcloud:fpm
          ports:
          -   containerPort: 9000
          #livenessProbe:
          #    httpGet:
          #      path: /
          #      port: 9000
          #    initialDelaySeconds: 30
          #    periodSeconds: 30
          #  readinessProbe:
          #    httpGet:
          #      path: /
          #      port: 9000
          #    initialDelaySeconds: 15
          #    periodSeconds: 3
