apiVersion: apps/v1
kind: Deployment

metadata:
  name: nextcloud-deployment
  labels:
    app: nextcloud

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:

      containers:
      - name: nextcloud
        imagePullPolicy: Always
        image: nextcloud:stable

        volumeMounts:
        - mountPath: "/var/www/html"
          name: nextcloud-persistent-volume
            
      volumes:
        - name: nextcloud-persistent-volume
          persistentVolumeClaim:
            claimName: nextcloud-pvc

      restartPolicy: Always
