apiVersion: v1
kind: Service
metadata:
    name: nextcloud-service
spec:
    type: NodePort
    selector:
        app: nextcloud
    ports:
    -   name: nextcloud-port
        targetPort: 80
        port: 80
        nodePort: 30001