# Service - LoadBalancer
apiVersion: v1
kind: Service
metadata:
    name: nginx-loadbalancer-service
spec:
    type: LoadBalancer
    selector:
        app: nginx-loadbalancer
    ports:
    -   name: nginx-loadbalancer-port
        targetPort: 30080
        port: 80
        nodePort: 80