apiVersion: apps/v1
kind: Deployment
metadata: 
    name: nginx-loadbalancer-deployment
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: nginx
        spec:
            nodeName: fra1-elliptic-loadbalancer-01
            containers:
            -   name: nginx-container
                image: malikiah-nginx
                ports:
                -   containerPort: 80
                livenessProbe:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 30
                  periodSeconds: 30
                readinessProbe:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 15
                  periodSeconds: 3
