# Service - LoadBalancer
apiVersion: v1
kind: Service
metadata:
    name: nginx-loadbalancer-service
spec:
    nodeName: fra1-elliptic-loadbalancer-01
    selector:
        app: nginx
    type: LoadBalancer
    ports:
    -   name: nginx-port
        targetPort: 80
        port: 80
        nodePort: 80