FROM nginx:latest

LABEL Damian Malikiah McCarthy

RUN apt-get -y update && apt-get -y upgrade && apt-get -y install git

#RUN echo "daemon off;" >> /etc/nginx/nginx.conf

#RUN git init
#RUN git config core.sparsecheckout true
#RUN echo nginx/conf.d/ > .git/info/sparse-checkout
#RUN git remote add origin -f https://github.com/Malikiah/kubernetes-resources.git
#RUN git pull origin master
RUN git clone https://github.com/Malikiah/kubernetes-resources.git

RUN mv kubernetes-resources/nginx/conf.d/* /etc/nginx/conf.d

RUN rm -rf kubernetes-resources

#RUN mkdir -p /var/www/html/nextcloud && chown -R nginx:nginx /var/www/html/nextcloud
EXPOSE 80
CMD ["nginx"]
