FROM fedora:29

MAINTAINER Damian Malikiah McCarthy

RUN dnf -y clean all && dnf -y update --releasever=29

RUN dnf -y install nginx libcurl

RUN echo "daemon off;" >> /etc/nginx/nginx.conf

RUN curl https://github.com/Malikiah/kubernetes-resources/tree/master/nginx/conf.d/nginx-proxy.conf > /etc/nginx/conf.d/nginx-proxy.conf

EXPOSE 80
CMD ["nginx"]