apiVersion: v1
kind: Service
metadata:
    name: nginx-service
spec:
    nodeName: fra1-elliptic-node-01
    selector:
        app: nginx
    ports:
    -   name: nginx-port
        nodeport: 30080
        port: 80
        targetport: 80
