apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  labels:
    app: nginx

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: malikiah1/nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nextcloud-persistent-volume
          mountPath: "/var/www/html/cloud.malikiah.io/nextcloud"
          
        - name: nextcloud-data-persistent-volume
          mountPath: "/var/www/html/cloud.malikiah.io/data"
          
      - name: php-fpm
        image: malikiah1/php7.2-fpm:latest
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: nextcloud-persistent-volume
          mountPath: "/var/www/html/cloud.malikiah.io/nextcloud"
            


      volumes:
      - name: nextcloud-persistent-volume
        persistentVolumeClaim:
          claimName: nextcloud-pvc

      - name: nextcloud-data-persistent-volume
        persistentVolumeClaim:
          claimName: nextcloud-data-pvc
              
      restartPolicy: Always