apiVersion: v1
kind: Service
metadata:
    name: nginx-nodeport-service
spec:
    type: NodePort
    selector:
        app: nginx
    ports:
    -   name: nginx-port
        targetPort: 80
        port: 80
        nodePort: 30080
