# Service - LoadBalancer
apiVersion: v1
kind: Service
metadata:
    name: nginx-service
spec:
    selector:
        app: nginx
    type: LoadBalancer
    ports:
    -   name: nginx-port
        port: 80
