apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  labels:
    app: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: malikiah/nginx-proxy:latest
        ports:
        - containerPort: 80
        livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 3

          volumeMounts:
          - name: nextcloud-persistent-volume
            mountPath: "/var/www/html/nextcloud"
            


      volumes:
      - name: nextcloud-persistent-volume
        persistentVolumeClaim:
          claimName: nextcloud-pvc
              
      restartPolicy: Always