apiVersion: apps/v1
kind: Deployment

metadata: 
    name: nginx-deployment
    labels:
      app: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        -   name: nginx
            image: malikiah/nginx-proxy:latest
            ports:
            -   containerPort: 80
            
        restartPolicy: Always