apiVersion: v1
kind: Service
metadata:
    name: nginx-service
spec:
    type: nodePort
    selector:
        app: nginx
    ports:
    -   name: nginx-port
        port: 80
        targetPort: 80
        nodeport: 30080
