apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-ingress-default-backend-network-policy
spec:
  podSelector:
    matchLabels:
      app: nginx-ingress-default-backend
  ingress:
  - {}