apiVersion: v1
kind: Service

metadata:
  name: nginx-ingress-controller
  labels:
    app: nginx-ingress-controller

spec:
  type: 'LoadBalancer'

  selector:
    app: nginx-ingress-controller

  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https