apiVersion: v1
kind: Service

metadata:
  name: nginx-ingress-service

spec:
  type: NodePort

  selector:
    app: nginx-ingress-controller

  ports:
  - name: http
    targetPort: 8080
    port: 8080
    nodePort: 30080
  - name: https
    targetPort: 8443
    port: 8443
    nodePort: 30443