apiVersion: v1
kind: Service

metadata:
  name: nginx-ingress-controller
  labels:
    app: nginx-ingress-controller

spec:
  type: NodePort

  selector:
    app: nginx-ingress-controller

  ports:
  - name: http
    port: 30080
    targetPort: http
    nodePort: 80
  - name: https
    port: 30443
    targetPort: https
    nodePort: 443