apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: nginx-ingress

spec:
  rules:
    - host: cloud.malikiah.io
      http:
        paths:
          - backend:
              serviceName: nextcloud
              servicePort: 9000
            path: /
  