FROM fedora:29
LABEL Damian Malikiah McCarthy

RUN dnf -y install mariadb-server mariadb git

RUN git clone https://github.com/Malikiah/kubernetes-resources.git

RUN ./kubernetes-resources/mariadb_secure_installation.sh
#RUN /usr/bin/mysql_secure_installation --port=3306 --password=$MARIADB_ROOT_PASSWORD

RUN sed -i 's/#bind-address=0.0.0.0/bind-address=0.0.0.0/' /etc/my.cnf.d/mariadb-server.cnf

CMD ["systemctl start mariadb"]                                                                                                                                                  