apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-persistent-volume
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 100Gi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: "/var/lib/mysql"