apiVersion: apps/v1
kind: Deployment

metadata:

  name: mariadb-deployment

  labels:
    app: mariadb

spec: 

  replicas: 2

  selector:
    matchLabels:
      app: mariadb

  template:
    
    metadata:
      labels:
        app: mariadb
    
    spec:
      containers:
      -   name: maria-db
          image: mariadb:latest
          ports:
            - containerPort: 3306
          args:
            - --transaction-isolation=READ-COMMITTED
            - --binlog-format=ROW
            - --max-connections=1000

          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: mariadb-secrets
          
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-persistent-storage

        restartPolicy: Always
        
        volumes:
          - name: mariadb-persistent-storage
            persistentVolumeClaim:
              claimName: mariadb-pvc