apiVersion: v1
kind: Secret

metadata:
  name: mariadb-secrets

type: Opaque

data:
  MARIADB_DATABASE: nextcloud_db
  MARIADB_USER: nextcloud
  MARIADB_PASSWORD: <any-base64-encoded-password>
  MARIADB_ROOT_PASSWORD: <a-different-base64-encoded-password>