apiVersion: v1
kind: Secret

metadata:
  name: mariadb-secrets

type: Opaque

data:
  MYSQL_DATABASE: nextcloud_db
  MYSQL_USER: nextcloud
  MYSQL_PASSWORD: <any-base64-encoded-password>
  MYSQL_ROOT_PASSWORD: <a-different-base64-encoded-password>