apiVersion: apps/v1
kind: Deployment

metadata:

  name: mariadb-deployment

  labels:
    app: mariadb

spec: 

  replicas: 2

  selector:
    matchLabels:
      app: mariadb

  template:
    
    metadata:
      labels:
        app: mariadb
    
    spec:
      containers:
      -   name: mariadb
          image: mariadb/server:latest
          ports:
            - containerPort: 3306
          args:
            - --transaction-isolation=READ-COMMITTED
            - --binlog-format=ROW
            - --max-connections=1000

          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root_password
                  name: mariadb-secrets
          
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mariadb-persistent-volume

            - mountPath: "/etc/mysql"
              name: mariadb-config-persistent-volume


          
      volumes:
          - name: mariadb-persistent-volume
            persistentVolumeClaim:
              claimName: mariadb-pvc

          - name: mariadb-config-persistent-volume
            persistentVolumeClaim:
              claimName: mariadb-config-pvc

      restartPolicy: Always
        