apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-config-persistent-volume
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 10Gi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: "/etc/mysql"