apiVersion: v1
kind: Service

metadata:
  name: mariadb-service

spec:
  clusterIP: 10.109.238.2
  type: ClusterIP
  selector:
    app: mariadb
    type: database
  ports:
  -   name: mariadb-port
      protocol: TCP
      port: 3306
  component: db