apiVersion: apps/v1
kind: Deployment

metadata:

  name: mariadb-deployment

  labels:
    app: mariadb

spec: 

  replicas: 2

  selector:
    matchLabels:
      app: mariadb

  template:
    
    metadata:
      labels:
        app: mariadb
    
    spec:
      containers:
      -   name: mariadb
          image: mariadb/server:latest
          ports:
            - containerPort: 3306
          args:
            - --transaction-isolation=READ-COMMITTED
            - --binlog-format=ROW
            - --max-connections=1000

          env:
            - name: MARIADB_NEXTCLOUD_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MARIADB_NEXTCLOUD_DATABASE
                  name: mariadb-secrets
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  key: MARIADB_NEXTCLOUD_USER
                  name: mariadb-secrets
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MARIADB_PASSWORD
                  name: mariadb-secrets
            - name: password
              valueFrom:
                secretKeyRef:
                  key: MARIADB_ROOT_PASSWORD
                  name: mariadb-secrets
          
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mariadb-persistent-volume

          
      volumes:
          - name: mariadb-persistent-volume
            persistentVolumeClaim:
              claimName: mariadb-pvc

      restartPolicy: Always
        