apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  MYSQL_DATABASE: #nextcloud
  MYSQL_USER: #nextcloud
    MYSQL_PASSWORD: <any-base64-encoded-password>
  MYSQL_ROOT_PASSWORD: <a-different-base64-encoded-password>